#!/usr/bin/env python3
"""Install the standard commit hook and Contract Tracer's multi-ref push hook."""

from __future__ import annotations

import os
import shlex
import subprocess
import sys
from pathlib import Path


PRE_COMMIT_MARKER = b"File generated by pre-commit"
PRE_PUSH_MARKER = b"Managed by Contract Tracer: multi-ref pre-push validation"


def git_output(repo_root: Path, *args: str, allow_failure: bool = False) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode and not allow_failure:
        raise RuntimeError(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout.strip()


def hooks_directory(repo_root: Path) -> Path:
    configured = git_output(repo_root, "config", "--path", "--get", "core.hooksPath", allow_failure=True)
    if configured:
        path = Path(configured)
        return (path if path.is_absolute() else repo_root / path).resolve()
    path = Path(git_output(repo_root, "rev-parse", "--git-path", "hooks"))
    return (path if path.is_absolute() else repo_root / path).resolve()


def _read_existing(path: Path) -> bytes | None:
    try:
        return path.read_bytes()
    except FileNotFoundError:
        return None


def _preflight_hooks(pre_commit_hook: Path, pre_push_hook: Path) -> None:
    existing = _read_existing(pre_commit_hook)
    if existing is not None and PRE_COMMIT_MARKER not in existing:
        raise RuntimeError(
            f"refusing to replace unrecognized hook {pre_commit_hook}; "
            "move it or chain it explicitly before installing Contract Tracer hooks"
        )

    for legacy in (pre_commit_hook.with_name(pre_commit_hook.name + ".legacy"), pre_push_hook.with_name(pre_push_hook.name + ".legacy")):
        if legacy.exists():
            raise RuntimeError(
                f"refusing to install hooks while legacy hook {legacy} exists; "
                "preserve or explicitly chain it before installing Contract Tracer hooks"
            )

    existing = _read_existing(pre_push_hook)
    if (
        existing is not None
        and PRE_COMMIT_MARKER not in existing
        and PRE_PUSH_MARKER not in existing
    ):
        raise RuntimeError(
            f"refusing to replace unrecognized hook {pre_push_hook}; "
            "move it or chain it explicitly before installing Contract Tracer hooks"
        )


def _shell_path(path: Path, *, resolve: bool = True) -> str:
    value = str(path.resolve()) if resolve else os.path.abspath(os.fspath(path))
    if os.name == "nt":
        value = value.replace("\\", "/")
    return shlex.quote(value)


def render_pre_push_hook(python_executable: str, script_path: Path) -> bytes:
    python_path = _shell_path(Path(python_executable), resolve=False)
    script = _shell_path(script_path)
    content = f"""#!/bin/sh
# {PRE_PUSH_MARKER.decode()}
# Reinstall or update this hook with: python tools/install_hooks.py
CONTRACT_TRACER_PYTHON={python_path}
CONTRACT_TRACER_SCRIPT={script}
exec "$CONTRACT_TRACER_PYTHON" "$CONTRACT_TRACER_SCRIPT" "$@"
"""
    return content.encode("utf-8")


def install_pre_push_hook(
    repo_root: Path,
    python_executable: str = sys.executable,
    script_path: Path | None = None,
) -> Path:
    repo_root = repo_root.resolve()
    if script_path is None:
        script_path = Path(__file__).with_name("pre_push.py")
    script_path = script_path.resolve()
    hook = hooks_directory(repo_root) / "pre-push"
    legacy = hook.with_name(hook.name + ".legacy")
    if legacy.exists():
        raise RuntimeError(
            f"refusing to install while legacy hook {legacy} exists; "
            "preserve or explicitly chain it before installing Contract Tracer hooks"
        )
    current = _read_existing(hook)
    if current is not None and PRE_COMMIT_MARKER not in current and PRE_PUSH_MARKER not in current:
        raise RuntimeError(
            f"refusing to replace unrecognized hook {hook}; "
            "move it or chain it explicitly before installing Contract Tracer hooks"
        )

    hook.parent.mkdir(parents=True, exist_ok=True)
    temporary = hook.with_name(hook.name + ".contract-tracer-tmp")
    temporary.write_bytes(render_pre_push_hook(python_executable, script_path))
    if os.name != "nt":
        temporary.chmod(0o755)
    os.replace(temporary, hook)
    return hook


def install_hooks(repo_root: Path, python_executable: str = sys.executable) -> None:
    repo_root = repo_root.resolve()
    hook_dir = hooks_directory(repo_root)
    pre_commit_hook = hook_dir / "pre-commit"
    pre_push_hook = hook_dir / "pre-push"
    _preflight_hooks(pre_commit_hook, pre_push_hook)

    result = subprocess.run(
        [python_executable, "-m", "pre_commit", "install", "--hook-type", "pre-commit"],
        cwd=repo_root,
        check=False,
    )
    if result.returncode:
        raise RuntimeError("pre-commit could not install the commit hook")
    install_pre_push_hook(repo_root, python_executable)


def main() -> int:
    repo_root = Path.cwd()
    try:
        git_output(repo_root, "rev-parse", "--show-toplevel")
        install_hooks(repo_root)
    except (OSError, RuntimeError) as exc:
        print(f"cannot install Contract Tracer hooks: {exc}", file=sys.stderr)
        return 1
    print("Installed pre-commit checks and the multi-ref pre-push hook.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
